bringup:
  angles:           degrees
  hz:               20

joints:

  l_wrist_roll_joint:
    minGoal:        180.0
    maxGoal:        0.0
    maxSpeed:       1000.0

  r_shoulder_lift_joint:
    minGoal:        45.0
    maxGoal:        -135.0
    maxSpeed:       100.0

  l_ring_joint:     
    minGoal:        -5.0
    maxGoal:        85.0
    maxSpeed:       1000.0

  l_index_joint:    
    minGoal:        -5.0
    maxGoal:        85.0
    maxSpeed:       1000.0
  
  head_roll_joint:  
    minGoal:        -15.0
    maxGoal:        15.0
    maxSpeed:       100.0

  r_thumb_joint:    
    minGoal:        -5.0
    maxGoal:        65.0
    maxSpeed:       1000.0

  r_wrist_roll_joint:
    minGoal:        0.0
    maxGoal:        -180.0
    maxSpeed:       1000.0

  l_middle_joint:   
    minGoal:        -5.0
    maxGoal:        85.0
    maxSpeed:       1000.0

  l_thumb_joint:    
    minGoal:        -5.0
    maxGoal:        65.0
    maxSpeed:       1000.0

  l_elbow_flex_joint:
    minGoal:        -15.0
    maxGoal:        -85.0
    maxSpeed:       100.0

  jaw_joint:        
    minGoal:        0.0
    maxGoal:        5.0
    maxSpeed:       100.0

  r_middle_joint:   
    minGoal:        -5.0
    maxGoal:        85.0
    maxSpeed:       1000.0

  r_elbow_flex_joint:
    minGoal:        -15.0
    maxGoal:        -80.0
    maxSpeed:       100.0

  eyes_pan_joint:   
    minGoal:        -30.0
    maxGoal:        30.0
    maxSpeed:       100.0

  r_ring_joint:     
    minGoal:        -5.0
    maxGoal:        85.0
    maxSpeed:       1000.0

  l_shoulder_lift_joint:
    minGoal:        45.0
    maxGoal:        -135.0
    maxSpeed:       100.0

  head_tilt_joint:  
    minGoal:        -20.0
    maxGoal:        20.0
    maxSpeed:       100.0

  r_index_joint:    
    minGoal:        -5.0
    maxGoal:        85.0
    maxSpeed:       1000.0

  l_pinky_joint:    
    minGoal:        -5.0
    maxGoal:        85.0
    maxSpeed:       1000.0

  head_pan_joint:   
    minGoal:        -100.0
    maxGoal:        90.0
    maxSpeed:       100.0

  r_pinky_joint:    
    minGoal:        -5.0
    maxGoal:        85.0
    maxSpeed:       1000.0

  l_shoulder_out_joint:
    minGoal:        5.0
    maxGoal:        60.0
    maxSpeed:       100.0

  waist_pan_joint:  
    minGoal:        -90.0
    maxGoal:        90.0
    maxSpeed:       100.0

  waist_roll_joint: 
    minGoal:        15.0
    maxGoal:        -15.0
    maxSpeed:       100.0

  r_upper_arm_roll_joint:
    minGoal:        90.0
    maxGoal:        -90.0
    maxSpeed:       100.0

  l_upper_arm_roll_joint:
    minGoal:        -90.0
    maxGoal:        90.0
    maxSpeed:       100.0

  eyes_tilt_joint:  
    minGoal:        15.0
    maxGoal:        -15.0
    maxSpeed:       100.0

  r_shoulder_out_joint:
    minGoal:        -5.0
    maxGoal:        -60.0
    maxSpeed:       100.0
