controller_manager:
  ros__parameters:
    update_rate: 1000  # 1 kHz to match 0.001 s sim step

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    inmoov_position_controller:
      type: position_controllers/JointGroupPositionController

joint_state_broadcaster:
  ros__parameters: {}

# Parameters for the group position controller (order matters!)
inmoov_position_controller:
  ros__parameters:
    joints:
      - waist_pan_joint
      - waist_roll_joint
      - head_roll_joint
      - head_tilt_joint
      - head_pan_joint
      - jaw_joint
      - eyes_tilt_joint
      - eyes_pan_joint
      - r_shoulder_lift_joint
      - r_upper_arm_roll_joint
      - r_elbow_flex_joint
      - r_shoulder_out_joint
      - r_wrist_roll_joint
      - l_shoulder_lift_joint
      - l_upper_arm_roll_joint
      - l_elbow_flex_joint
      - l_shoulder_out_joint
      - l_wrist_roll_joint
      - l_thumb_joint
      - l_index_joint
      - l_middle_joint
      - l_ring_joint
      - l_pinky_joint
      - r_thumb_joint
      - r_index_joint
      - r_middle_joint
      - r_ring_joint
      - r_pinky_joint
    command_interfaces: [position]
    state_interfaces:   [position]   # add velocity here if you want it published too
    state_publish_rate: 50.0

# Gazebo Sim (gz_ros_control) plugin parameters
gz_ros_control:
  ros__parameters:
    hold_joints: false
    position_proportional_gain: 200.0  # tune as needed; try 300–800 if too stiff
