controller_manager:
  ros__parameters:
    update_rate: 250

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # One controller to move everything with /inmoov_pos_cmd/commands
    inmoov_position_controller:
      type: position_controllers/JointGroupPositionController

# Parameters for that controller (order matters!)
inmoov_position_controller:
  ros__parameters:
    joints:
      - waist_pan_joint
      - waist_roll_joint
      - head_roll_joint
      - head_tilt_joint
      - head_pan_joint
      - jaw_joint
      - eyes_tilt_joint
      - eyes_pan_joint
      - r_shoulder_lift_joint
      - r_upper_arm_roll_joint
      - r_elbow_flex_joint
      - r_shoulder_out_joint
      - r_wrist_roll_joint
      - l_shoulder_lift_joint
      - l_upper_arm_roll_joint
      - l_elbow_flex_joint
      - l_shoulder_out_joint
      - l_wrist_roll_joint
      - l_thumb_joint
      - l_index_joint
      - l_middle_joint
      - l_ring_joint
      - l_pinky_joint
      - r_thumb_joint
      - r_index_joint
      - r_middle_joint
      - r_ring_joint
      - r_pinky_joint
    command_interfaces: [position]
    state_interfaces:   [position]
    state_publish_rate: 50.0

# Gazebo Sim plugin startup params (the few it actually reads as ROS params)
gz_ros_control:
  ros__parameters:
    hold_joints: false
    position_proportional_gain: 60.0
