controller_manager:
  ros__parameters:
    update_rate: 250

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    inmoov_position_controller:
      type: position_controllers/JointGroupPositionController

inmoov_position_controller:
  ros__parameters:
    joints:
      - head_roll_joint
      - head_tilt_joint
    command_interfaces:
      - position